### ISSUE TITLE
Clicking on the Deploy to Heroku button raises an exception: can't find pgbackups.

### ISSUE THREAD

**Issue by imf** [city72/city-72#148]
The Heroku dashboard complains:

There was a problem with the app.json file found at "https://github.com/city72/city-72":
The addon "pgbackups" does not exist. Please ensure that the addon is spelled correctly.

**Comment by arena** [comment]
Thanks for finding this Ian! 

@friism 
Did something change with Heroku that might have caused this?
..or do you think something in the City72 codebase was accidentally changed?

**Comment by friism** [comment]
@arena yeah, you no longer need that add-on: https://devcenter.heroku.com/changelog-items/623

**Comment by arena** [comment]
@friism I never actually looked at the code in the Heroku Button related files. Is this just a matter of removing a line or two?

**Comment by arena** [comment]
@friism ps - THANK YOU for responding and knowing what is going on. :)

**Comment by arena** [comment]
Thanks @imf for finding and @friism for fixing. Issue closed. :)
